---
title: Guillermo de la Puente
timezone: UTC
collections:
  posts:
    title: Blog
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/blog/:title/"
    show_subscribe_button: 1
- scope:
    path: ''
  values:
    google_analytics_tracking_id: UA-130643092-1
    subscribe_url: "/subscribe"
    app_background_color: rgb(35, 39, 45)
    app_font_body_color: rgb(220, 220, 220)
    app_font_body_color_hover: rgb(255, 255, 255)
    app_font_body_secondary_color: "#888"
    app_font_link_color: rgb(230, 187, 70)
    app_font_link_color_hover: "#F0D690"
