---
title: Guillermo de la Puente
timezone: UTC
collections:
  posts:
    title: Blog
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: posts
    type: posts
  values:
    layout: default
    permalink: "/blog/"
- scope:
    path: '' # all files in the project
    type: posts
  values:
    layout: post
    permalink: "/blog/:title/"
- scope:
    path: '' # all files in the project
  values:
    google_analytics_tracking_id: "UA-130643092-1"